###---Posts APIs---###

###Add a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
  "content": "This is my first post",
  "sender": "Ofri and Amit2"
}

###Get all posts
GET http://localhost:3000/posts

###Get a post by ID
GET http://localhost:3000/posts/696b9dc4a47fa6602979d47a

###Get a post by sender
GET http://localhost:3000/posts/sender/Ofri and Amit

###Update a post by ID
PUT http://localhost:3000/posts/696b9dc4a47fa6602979d47a
Content-Type: application/json

{
  "content": "This is my updated post content",
  "sender": "Ofri and Amit"
}



###---Comments APIs---###

###Add a new comment to a post
POST http://localhost:3000/comments
Content-Type: application/json

{
  "content": "This is my first comment",
  "sender": "Amit1 and Ofri1",
  "postId": "696b9dc4a47fa6602979d47a"
}

###Get all comments for a specific post
GET http://localhost:3000/comments?postId=696b9dc4a47fa6602979d47a

###Get a comment by ID
GET http://localhost:3000/comments/696bc1f67111a7e5ca0d612c

###Update a comment by ID
PUT http://localhost:3000/comments/696bc1f67111a7e5ca0d612c
Content-Type: application/json

{
  "content": "This is my updated comment content",
  "sender": "Amit1 and Ofri1",
  "postId": "696b9dc4a47fa6602979d47a"
}

###Delete a comment by ID
DELETE http://localhost:3000/comments/696bc1f67111a7e5ca0d612c